import NextAuthProvider from "@/components/providers/NextAuthProvider";
import NextUiProviders from "@/components/providers/NextUiProvider";
import TanstackProvider from "@/components/providers/TanstackProvider";
import "@styles/globals.css";
import { MessagesProvider } from "context/messages.context";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body >
        <TanstackProvider>
          <MessagesProvider>
            <NextUiProviders>
              <NextAuthProvider>
                {children}
              </NextAuthProvider>
            </NextUiProviders>
          </MessagesProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
